server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://${HOST_IP_ADDRESS}:3306/springcloud?createDatabaseIfNotExist=true
    username: root
    password: nathan2709
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.show_sql: true
        hibernate.format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: true
      oauth2:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          statistic-service:
            authorizationGrantType: client_credentials
            clientId: accountservice
            clientSecret: 123
            scope: log
            provider: spring
          notification-service:
            authorizationGrantType: client_credentials
            clientId: accountservice
            clientSecret: 123
            scope: notification
            provider: spring
        provider:
          spring:
            issuer-uri: http://${HOST_IP_ADDRESS}:9000

#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000

#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 5s
#        cancel-running-future: true


