#config for discovery service
eureka:
  client:
    service-url:
      defaultZone: http://${HOST_IP_ADDRESS}:9999/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP_ADDRESS}

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: false


#expose all the actuator endpoint for monitoring the server health
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${HOST_IP_ADDRESS}:9411/api/v2/spans

logging:
  level:
    root: INFO
  file:
    name: myapp.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  include-application-name: false

spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #oauth 2 security
          issuer-uri: http://${HOST_IP_ADDRESS}:9000
          #public jwt keys
          jwk-set-uri: http://${HOST_IP_ADDRESS}:9000/oauth2/jwks